"""Per-tool name, description, and parameter schema constants."""

from .bash import BASH_CWD_MARKER, BASH_DESCRIPTION, BASH_NAME, BASH_PARAMETERS
from .edit_file import EDIT_FILE_DESCRIPTION, EDIT_FILE_NAME, EDIT_FILE_PARAMETERS
from .list_dir import LIST_DIR_DESCRIPTION, LIST_DIR_NAME, LIST_DIR_PARAMETERS, LIST_DIR_SKIP_DIRS
from .read_file import READ_FILE_DESCRIPTION, READ_FILE_NAME, READ_FILE_PARAMETERS
from .write_file import WRITE_FILE_DESCRIPTION, WRITE_FILE_NAME, WRITE_FILE_PARAMETERS

__all__ = [
    "BASH_CWD_MARKER",
    "BASH_DESCRIPTION",
    "BASH_NAME",
    "BASH_PARAMETERS",
    "EDIT_FILE_DESCRIPTION",
    "EDIT_FILE_NAME",
    "EDIT_FILE_PARAMETERS",
    "LIST_DIR_DESCRIPTION",
    "LIST_DIR_NAME",
    "LIST_DIR_PARAMETERS",
    "LIST_DIR_SKIP_DIRS",
    "READ_FILE_DESCRIPTION",
    "READ_FILE_NAME",
    "READ_FILE_PARAMETERS",
    "WRITE_FILE_DESCRIPTION",
    "WRITE_FILE_NAME",
    "WRITE_FILE_PARAMETERS",
]
